ALTER TABLE orders ADD COLUMN sku VARCHAR(80) NOT NULL DEFAULT 'SKU-LAPTOP-001';
ALTER TABLE orders ADD COLUMN quantity INTEGER NOT NULL DEFAULT 1;
ALTER TABLE orders ADD CONSTRAINT chk_orders_quantity CHECK (quantity > 0);