spring:
  application:
    name: inventory-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/inventory}
    username: ${DB_USERNAME:inventory}
    password: ${DB_PASSWORD:inventory}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: com.sajjantawar.*
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
server:
  port: ${SERVER_PORT:8082}